name: Build BugScannerOS CLI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Tools Build
      run: sudo apt-get update && sudo apt-get install -y wget cpio gzip xorriso busybox-static curl nmap

    - name: Download Kernel + Siapin Folder
      run: |
        mkdir -p iso rootfs/bin rootfs/sbin rootfs/usr/bin rootfs/boot rootfs/lib
        wget http://tinycorelinux.net/15.x/x86/release/distribution_files/vmlinuz -O iso/vmlinuz

    - name: Copy Busybox + curl + nmap
      run: |
        cp /bin/busybox rootfs/bin/busybox
        for i in sh mount ln; do ln -s busybox rootfs/bin/$i; done
        
        cp /usr/bin/curl rootfs/usr/bin/curl
        cp /usr/bin/nmap rootfs/usr/bin/nmap
        ldd /usr/bin/curl /usr/bin/nmap | grep "=> /" | awk '{print $3}' | xargs -I {} cp -v {} rootfs/lib/ 2>/dev/null || true

    - name: Buat init
      run: |
        echo '#!/bin/sh' > rootfs/init
        echo 'mount -t proc /proc' >> rootfs/init
        echo 'mount -t sysfs /sys' >> rootfs/init
        echo 'mount -t devtmpfs /dev' >> rootfs/init
        echo 'echo "BugScannerOS CLI Ready. Ketik: curl / nmap"' >> rootfs/init
        echo '/bin/sh' >> rootfs/init
        chmod +x rootfs/init
        ln -s /init rootfs/sbin/init  # <-- INI PENTING

    - name: Pack to ISO
      run: |
        cd rootfs && find . | cpio -o -H newc | gzip > ../iso/rootfs.gz
        cd ../iso && xorriso -as mkisofs -o BugScanner-CLI.iso -b vmlinuz .

    - name: Upload ISO
      uses: actions/upload-artifact@v4
      with:
        name: BugScanner-CLI
        path: iso/BugScanner-CLI.iso
