name: Remaster Disk Image

on: workflow_dispatch

jobs:
  remaster:
    runs-on: ubuntu-22.04
    steps:
      - name: Download Artifacts
        uses: actions/Download-artifact@v4
        with:
         name: x86-minimal-linux
         path: |
          buildroot/output/images/bzImage
          buildroot/output/images/rootfs.
          
      - name: Install deps for making bootable disk
        run: |
          sudo apt-get update
          sudo apt-get install -y grub-pc-bin mtools dosfstools parted qemu-utils

      - name: Create bootable disk.img
        run: |
          mkdir -p mnt/boot mnt/root
          
          # 1. Bikin file disk.img kosong 512MB
          dd if=/dev/zero of=disk.img bs=1M count=512
          
          # 2. Bikin tabel partisi MBR + 1 partisi bootable
          parted -s disk.img mklabel msdos
          parted -s disk.img mkpart primary ext2 1MiB 100%
          parted -s disk.img set 1 boot on
          
          # 3. Mount disk.img pake loop
          LOOP=$(sudo losetup -fP --show disk.img)
          sudo mkfs.ext2 ${LOOP}p1 -L root
          
          # 4. Copy rootfs.ext2 ke partisi
          sudo mount ${LOOP}p1 mnt/root
          sudo tar -xf files/rootfs.ext2 -C mnt/root
          
          # 5. Install GRUB ke disk.img
          sudo grub-install --target=i386-pc --boot-directory=mnt/root/boot --modules="biosdisk part_msdos ext2" $LOOP
          
          # 6. Bikin grub.cfg
          sudo mkdir -p mnt/root/boot/grub
          cat <<EOF | sudo tee mnt/root/boot/grub/grub.cfg
          set timeout=0
          menuentry "Buildroot" {
              linux /boot/bzImage root=/dev/sda1 console=ttyS0
          }
          EOF
          
          # 7. Copy kernel bzImage ke /boot
          sudo cp files/bzImage mnt/root/boot/bzImage
          
          # 8. Umount
          sudo umount mnt/root
          sudo losetup -d $LOOP

      - name: Upload Bootable Disk Image
        uses: actions/upload-artifact@v4
        with:
          name: x86-remastered-bootable
          path: disk.img
          retention-days: 14
